development:
  session_key: pod_development
  session_secret: ESl6X3oKM1i1RRrD2QLwUUzz9jr1zxNO
  domain: http://example.com

test:
  session_key: pod_test
  session_secret: vrwPpJTvwnMVLP1wTSgqigSl7PMI7QcE
  domain: http://example.com
  
production:
  # SESSION SETTINGS (required)
  # More info: http://guides.rubyonrails.org/security.html#session-storage
  session_key: pod_development # a unique string that identifies your app
  session_secret: vrwPpJTvwnMVLP1wTSgqigSl7PESl6X3oKM1i1RRrD2QLwUUzz9jr1zxNO # a random string, at least 32 characters long, that should be unique to your installation and kept secret
  
  # APPLICATION SETTINGS (required)
  domain: http://pod.oceanshore.org # http://example.com # the url for your application
  mailer: forum@oceanshore.org      # noreply@example.com # the from address for subscription emails (users can subscribe to forum threads)
  
  # AMAZON S3 (optional, required for Heroku)  
  # More info from Heroku: http://docs.heroku.com/constraints#read-only-filesystem
  # Visit the Amazon S3 site to sign up for an access_id and secret_key: https://s3.amazonaws.com/
  # The bucket name can be any unique string, and once set here it can be created by running "rake s3:create" 
  s3_access_id: 0XVAQR64TGCGWZ4W37R2
  s3_secret_key: 2mkUk7BxE4fVu7J4zCmVGnhIL3kXQGn8GaEpl5QR
  s3_bucket_name: podoceanshore
  
  # EMAIL SETTINGS (optional, required for Heroku)
  # More info from Heroku: http://support.heroku.com/forums/43117/entries/32352
  # These example settings would use a normal Gmail account, but other options are available...
  smtp_address: smtp.gmail.com 
  smtp_port: 587
  smtp_user_name: oceanshore.org@gmail.com # example@gmail.com
  smtp_password: melorbode # password
  smtp_authentication: plain
  smtp_enable_starttls_auto: true
  smtp_domain: # example.com # omit if using a normal Gmail account